### ISSUE TITLE
Bridge doesn't let me join Freenode channel with key

### ISSUE THREAD

**Issue by WillPittenger** [matrix-org/matrix-appservice-irc#1175]
**Describe the bug**
I need to join a Freenode channel where a key is required.  So I send @appservice-irc:matrix.org `!join #channame chankey`.  Nothing happens.

**To Reproduce**
1. /msg @appservice-irc:matrix.org
2. Send `!join #channame chankey`
3. What happens?

**Expected behavior**
I should see an invite to the requested channel.  I'd also expect an offer to remember the key.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 64-bit
 - Element Desktop 1.7.12

**Comment by jaller94** [comment]
Same as #1286 and presumably fixed by https://github.com/vector-im/element-web/issues/16829.

**Comment by Half-Shot** [comment]
Not fixed, ref https://github.com/matrix-org/matrix-appservice-irc/issues/1286#issuecomment-1129836931 but yes a duplicate.
