### ISSUE TITLE
Fix support for password protected rooms

### ISSUE THREAD

**Issue by robertfoss** [matrix-org/matrix-appservice-irc#1286]
**Describe the bug**

There are two somewhat separate issues that I've found
 - There is no (documented?) way of joining password protected irc channels through the `Explore Public Rooms` menu
   * This can be worked around by issuing a `!join #channel password` to `@appservice-irc:matrix.org`
 - However this password is not remember when the room is reconnected to (after an irc server restart for example), so this room will fail to connect and will be removed from the rooms list silently without notifying the user.

**To Reproduce**

- Manually join password protected irc channel by sending `!join #channel password` to `@appservice-irc:matrix.org`
- Wait for irc server to restart
- After restart is completed only non-password protected irc channels will be rejoined and listed in your rooms view.

**Expected behavior**

I would expect the password associated with a channel to be stored wherever my irc channel membership list is stored, or possibly where the irc server password is stored.

For the web app:

- **Browser**: Chrome, Firefox, Safari, Edge? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: matrix.org

For the desktop app:

- **OS**: Ubuntu 20.10
- **Version**: Element version: 1.7.23

**Comment by jaller94** [comment]
Presumably fixed by https://github.com/vector-im/element-web/issues/16829

Untested.

**Comment by robertfoss** [comment]
This issue still exists. Channel passwords are not stored anywhere.

```
Could not join #linaro-lt-qcom on '[irc.oftc.net](http://irc.oftc.net/)': err_badchannelkey
```

**Comment by Half-Shot** [comment]
I don't think this is fixed. The upstream issue was redirected here.
