### ISSUE TITLE
Setting up IRC Matrix Bridge Fails: "Failed to make link: Cannot read property 'users' of undefined"

### ISSUE THREAD

**Issue by BullShark** [matrix-org/matrix-appservice-irc#1496]
**Describe the bug**
I always get an error or strange message when trying to setup an irc matrix bridge to ##blackhats:matrix.org.

**To Reproduce**
1. Go to 'Add widgets, bridges & bots'
2. Click on 'Add integrations'
3. Scroll down to 'Bridges, IRC'

**Expected behavior**
I expect the MatrixBridge bot to ask me to confirm the bridge in the irc channel and to join nicks from matrix to irc and irc to matrix. Instead the bot joins the channel and immediately leaves. Then I get an error or weird message.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Manjaro KDE Plasma
 - Browser Element from the repos
 - Version 
element-desktop 1.8.5-1
element-web 1.8.5-1

 **Smartphone (please complete the following information):**
N/A

**Additional context**
No other info for now.
![Screenshot_20211116_113839-0 is not of type integer](https://user-images.githubusercontent.com/1526595/142037671-fb0fa6ba-7bae-4bbb-b3c5-3d4aa21339c5.png)
![image](https://user-images.githubusercontent.com/1526595/142037677-36c3259c-d1f2-4f74-ae02-e67cab72136f.png)
![Screenshot_20211113_201226-Failed to make link](https://user-images.githubusercontent.com/1526595/142037681-b6d0124f-325b-45ca-b6df-2222b1c16574.png)
![Screenshot_20211113_201057-Unexpected token](https://user-images.githubusercontent.com/1526595/142037689-bfa12f44-bac8-4a9c-bed4-feb02a3405af.png)

**Comment by Aerol** [comment]
Happening to me as well.

**Comment by BullShark** [comment]
I'm no longer getting those errors. I'm now getting this error.


![image](https://user-images.githubusercontent.com/1526595/144149207-e82bf28a-26fc-4b0c-b5f2-d0f1912e4e58.png)

**Comment by BullShark** [comment]
"Failed to make link: Cannot read property 'users' of undefined"

**Comment by Half-Shot** [comment]
Fixed in https://github.com/matrix-org/matrix-react-sdk/pull/7179

**Comment by eukara** [comment]
> I'm no longer getting those errors. I'm now getting this error.
> 
> ![image](https://user-images.githubusercontent.com/1526595/144149207-e82bf28a-26fc-4b0c-b5f2-d0f1912e4e58.png)

Still getting this problem. Trying to bridge #freecs:matrix.org and to liberachat is not working.

**Comment by Half-Shot** [comment]
You'll need to wait for the above PR to be released / use nightly|develop Element for this to work.

**Comment by eukara** [comment]
Okay! I didn't quite understand whether this was a server/client issue.
