### ISSUE TITLE
#freenode_#twisted:matrix.org is stuck in some horrid limbo state

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#174]

**Comment by dtzWill** [comment]
This still appears to be a problem:

https://riot.im/app/#/room/#freenode_#twisted:matrix.org

Room appears entirely disjoint from the freenode channel, and is currently empty other than @ara4n and myself.

**Comment by ara4n** [comment]
I fixed it, given nobody else seems likely to atm.  i removed the #freenode_#twisted:matrix.org alias from the broken room (`!IcobSccKHPqvQHleQK:matrix.org`); no idea how it ended up in that state; perhaps a confused attempt to plumb a portal room), and then changed the invite rule on the real version of the room (`!LvhsKwqoPTdLCCrJzF:matrix.org`) by injecting an event.  It now seems okay, although I have no idea how the 'real' room ended up as invite-only.

**Comment by Mikaela** [comment]
@ara4n Could you also take a look at https://github.com/matrix-org/matrix-appservice-irc/issues/187 in case it wasn't fixed yet?

**Comment by ara4n** [comment]
ah, well #187 at least explains why the join_rule state was wrong - apparently if you joined a room via !join it would set the wrong join_rules.
