### ISSUE TITLE
Matrix ←→ IRC name translation woes, leaks local representation

### ISSUE THREAD

**Issue by madduck** [matrix-org/matrix-appservice-irc#634]
I am joined into several IRC channels via Matrix, and the following is a common interaction:

> **nick(IRC)**    
> madduck[m]: how are you?  
>   
> **madduck**  
> nick(IRC): good as, and you?  

On the IRC side of things, this will look similar to this:

```
< nick> madduck[m]: how are you?
< madduck[m]> nick(IRC): good as, and you?
```

Generally speaking, that's all good and well, but could be enhanced in the following two ways:

1. In messages from IRC to Matrix, which start out with the Matrix user's mapped IRC nickname, followed by a punctuation character, the nickname could be replaced with the Matrix user's name, i.e. `madduck[m]` becomes `madduck` in the above, and is rendered as such in e.g. Riot. It's even debatable if this replacement shouldn't happen to the name as it appears anywhere on the line, but certainly it should happen at the start.

2. In messages from Matrix to IRC, given that the bridge added `(IRC)` to distinguish IRC nicknames within the Matrix client, outgoing messages should have the `(IRC)` appendix stripped on obvious mentions, and possibly even for all occurrences on a line.

Thanks for your consideration,
-martin

**Comment by Half-Shot** [comment]
>In messages from Matrix to IRC, given that the bridge added (IRC) to distinguish IRC nicknames within the Matrix client, outgoing messages should have the (IRC) appendix stripped on obvious mentions, and possibly even for all occurrences on a line.

For 2, we are already in the phase of stripping (IRC) in favor of showing IRC users as group members in Riot. So that should be fixed.

**Comment by fcrozat** [comment]
Unfortunately, 2 isn't fully fixed, due to the drop of the hacks in latest matrix-react-sdk (visible with Riot v0.17.x).

Right now, on IRC side, you get:
< nick> madduck[m]: how are you?
< madduck[m]> nick (IRC)  good as, and you?

which was not happening with Riot v0.16.x
