### ISSUE TITLE
Nick with { or } show up "=7B" and "=7D"

### ISSUE THREAD

**Issue by kroeckx** [matrix-org/matrix-appservice-irc#749]
Someone with the nick `{hoshi}` on IRC shows up as `_ircnet_=7bhoshi=7d` in the room. Everything related to that nick is shown as that.

**Comment by Half-Shot** [comment]
This is correct for the user_id, but not for the display name. Can you screenshot it / show me the users member state?

**Comment by kroeckx** [comment]
Message from the user:
![message](https://user-images.githubusercontent.com/1616242/56909909-8c74e880-6aa9-11e9-9324-06772af88e77.png)

Details of the user:
![user](https://user-images.githubusercontent.com/1616242/56909916-91399c80-6aa9-11e9-8eed-3438d3d3d777.png)

Is that what you're looking for?

**Comment by Mikaela** [comment]
Duplicate of https://github.com/matrix-org/matrix-appservice-irc/issues/498?

**Comment by joepie91** [comment]
@Mikaela I'm getitng this issue on Freenode (see https://github.com/vector-im/riot-web/issues/9771), so it's probably a different issue (given that #498 explicitly mentions that Freenode is not affected).

**Comment by Half-Shot** [comment]
This is a bit different. I believe it's because we now escape nicks for the purpose of shoving them in mxids (Matrix forbids a lot of characters, and we've been abusing this for years). My theory is that the displayname of IRC users is being wrongfully set to the localpart of their mxid.

**Comment by Half-Shot** [comment]
This is fixed by https://github.com/matrix-org/matrix-appservice-irc/pull/750

**Comment by mfiano** [comment]
This also seems to affect nicks containing pipe (`|`) characters. On the current Riot web version, this is still an issue.

**Comment by Mikaela** [comment]
@mfiano Have you seen https://github.com/matrix-org/matrix-appservice-irc/issues/767 ? I wonder if you referred to it or it has gotten more broken since May the 23th.

**Comment by Ralith** [comment]
> My theory is that the displayname of IRC users is being wrongfully set to the localpart of their mxid.

I've been seeing `@freenode_=7b^_^=7d:matrix.org` show up as `=7b^_^=7d` for months; note that this is *not* the localpart of the mxid.

**Comment by Half-Shot** [comment]
FYI #768 hopes to disable the feature entirely until I have more time to make the whole IRC bridge cooperate with escaping.

**Comment by Half-Shot** [comment]
Closing this PR, please use #744 for reporting issues of this type as they seem to all be related.
